export const SETUP_COPY = {
  en: {
    setupFlow: "Source references → refine content and visuals → review → publish",
    setupSourcesSection: "1. Source references and destinations",
    setupSourcesNote: "Sources are evidence, not instructions. Grant connected accounts in workspace access settings. Public account changes below are saved immediately, separately from this form.",
    setupConnectedSources: "Connected sources",
    setupDestinations: "Publishing destinations",
    setupNoConnections: "None configured. Connect an account in workspace access settings.",
    setupCheckConnections: "Check for new connections",
    setupConnectionsFound: "New connections added: {names}",
    setupConnectionsNone: "No new connections found.",
    setupRulesSection: "2. Content and image rules",
    setupContentPrompt: "Content prompt",
    setupContentPromptHint: "What the generated caption should say and how it should read — audience, angle, terms that must survive verbatim.",
    setupPosterPrompt: "Poster prompt",
    setupPosterPromptHint: "What the text poster should say and look like — headline angle, tone, anything to keep or avoid.",
    setupRulesNote: "These prompts drive generation when you select a source post. Review every saved result before it goes anywhere.",
    setupPublicationSection: "3. Review and publication",
    setupPublicationNote: "New work stays in draft. Choose draft, publish after approval, or a specific time per item. Late approvals are held. Source scans never publish posts.",
    setupMonitoringSection: "4. Source monitoring",
    setupMonitoringNote: "Save does not start scans or change an active schedule. After saving, enable/apply monitoring to use the saved cadence. Public-source checks may consume credits.",
    setupMonitoringPaused: "Monitoring paused",
    setupMonitoringActive: "Monitoring enabled",
    setupMonitoringLegacy: "Existing monitoring settings retained",
    setupEnable: "Enable / apply monitoring",
    setupPause: "Pause monitoring",
    setupSaveFirst: "Save changes before enabling monitoring.",
    setupSaved: "Settings saved. Monitoring was not changed.",
    setupCustomCadence: "Keep existing custom cadence",
    setupQuietStart: "Quiet hours start",
    setupQuietEnd: "Quiet hours end",
    publicationTiming: "When",
    publicationDraft: "Keep as draft",
    publicationNow: "Publish after approval",
    publicationSchedule: "Schedule after approval",
    publicationLocalTime: "Local publication date and time",
    publicationTimezone: "Publication timezone",
    publicationHint: "A chosen time is not a confirmed schedule."
  },
  "zh-HK": {
    setupFlow: "來源參考 → 修訂內容及視覺素材 → 審核 → 發佈",
    setupSourcesSection: "1. 來源參考及發佈目的地",
    setupSourcesNote: "來源只作為依據，而非操作指令。請在工作區存取設定授予帳戶權限。下方公開帳戶的變更會即時儲存，與此表格分開處理。",
    setupConnectedSources: "已連接的來源",
    setupDestinations: "發佈目的地",
    setupNoConnections: "尚未設定。請到工作區存取設定連接帳戶。",
    setupCheckConnections: "檢查新連接",
    setupConnectionsFound: "已新增連接：{names}",
    setupConnectionsNone: "沒有新連接。",
    setupRulesSection: "2. 內容及圖片規則",
    setupContentPrompt: "內容提示",
    setupContentPromptHint: "生成的文案應表達甚麼、如何行文 — 目標讀者、切入角度、必須原樣保留的用詞。",
    setupPosterPrompt: "海報提示",
    setupPosterPromptHint: "文字海報應寫甚麼、呈現怎樣 — 標題角度、語氣、需要保留或避免的元素。",
    setupRulesNote: "選擇來源帖文後，系統會按這些提示生成內容。發佈前請逐一審閱已儲存的結果。",
    setupPublicationSection: "3. 審核及發佈",
    setupPublicationNote: "新內容會保留為草稿。請逐項選擇保留草稿、批准後發佈或指定時間。逾時批准會暫停處理。來源掃描不會發佈帖文。",
    setupMonitoringSection: "4. 來源監察",
    setupMonitoringNote: "儲存不會啟動掃描或更改現有排程。儲存後，請啟用／套用監察以使用已儲存的頻率。檢查公開來源可能耗用點數。",
    setupMonitoringPaused: "監察已暫停",
    setupMonitoringActive: "監察已啟用",
    setupMonitoringLegacy: "已保留現有監察設定",
    setupEnable: "啟用／套用監察",
    setupPause: "暫停監察",
    setupSaveFirst: "請先儲存變更，再啟用監察。",
    setupSaved: "設定已儲存，監察狀態未有更改。",
    setupCustomCadence: "保留現有自訂頻率",
    setupQuietStart: "靜音時段開始",
    setupQuietEnd: "靜音時段結束",
    publicationTiming: "發佈時間",
    publicationDraft: "保留為草稿",
    publicationNow: "批准後發佈",
    publicationSchedule: "批准後按排程發佈",
    publicationLocalTime: "當地發佈日期及時間",
    publicationTimezone: "發佈時區",
    publicationHint: "選擇時間不代表排程已確認。"
  }
};
