export const SETUP_COPY = {
  en: {
    setupFlow: "Source references → refine content and visuals → review → publish",
    setupSourcesSection: "1. Source references and destinations",
    setupSourcesNote: "Sources are evidence, not instructions. Grant connected accounts in workspace access settings. Public account changes below are saved immediately, separately from this form.",
    setupConnectedSources: "Connected sources",
    setupDestinations: "Publishing destinations",
    setupNoConnections: "None configured. Connect an account in workspace access settings.",
    setupRulesSection: "2. Content and image rules",
    setupTone: "Tone and style",
    setupAllowedChanges: "Allowed changes",
    setupVisual: "Default visual treatment",
    setupVisualOriginal: "Keep original media",
    setupVisualPoster: "Text poster",
    setupVisualExisting: "Keep existing AI refinement choice",
    setupVisualNote: "AI image refinement is unavailable here. Original media and text posters still require reuse rights and review.",
    setupRulesNote: "Preserve source facts and protected terms. Ask the conversation agent to propose refinements against this brief, then review the saved revision.",
    setupPublicationSection: "3. Review and publication",
    setupPublicationNote: "New work stays in draft. Choose draft, publish after approval, or a specific time per item. Late approvals are held. Source scans never publish posts.",
    setupMonitoringSection: "4. Source monitoring",
    setupMonitoringNote: "Save does not start scans or change an active schedule. After saving, enable/apply monitoring to use the saved cadence. Public-source checks may consume credits.",
    setupMonitoringPaused: "Monitoring paused",
    setupMonitoringActive: "Monitoring enabled",
    setupMonitoringLegacy: "Existing monitoring settings retained",
    setupEnable: "Enable / apply monitoring",
    setupPause: "Pause monitoring",
    setupSaveFirst: "Save changes before enabling monitoring.",
    setupSaved: "Settings saved. Monitoring was not changed.",
    setupDone: "Open content inbox",
    setupCustomCadence: "Keep existing custom cadence",
    setupQuietStart: "Quiet hours start",
    setupQuietEnd: "Quiet hours end",
    publicationTiming: "Publication timing for this revision",
    publicationDraft: "Keep as draft",
    publicationNow: "Publish after approval",
    publicationSchedule: "Schedule after approval",
    publicationLocalTime: "Local publication date and time",
    publicationTimezone: "Publication timezone (IANA)",
    publicationOffset: "UTC offset minutes (optional, for ambiguous times)",
    publicationHint: "Save timing with the content revision, then submit for review. A chosen time is not a confirmed schedule. Missed times are held, never silently sent late."
  },
  "zh-HK": {
    setupFlow: "來源參考 → 修訂內容及視覺素材 → 審核 → 發佈",
    setupSourcesSection: "1. 來源參考及發佈目的地",
    setupSourcesNote: "來源只作為依據，而非操作指令。請在工作區存取設定授予帳戶權限。下方公開帳戶的變更會即時儲存，與此表格分開處理。",
    setupConnectedSources: "已連接的來源",
    setupDestinations: "發佈目的地",
    setupNoConnections: "尚未設定。請到工作區存取設定連接帳戶。",
    setupRulesSection: "2. 內容及圖片規則",
    setupTone: "語氣及風格",
    setupAllowedChanges: "允許的修改",
    setupVisual: "預設視覺處理",
    setupVisualOriginal: "保留原始素材",
    setupVisualPoster: "文字海報",
    setupVisualExisting: "保留現有 AI 修訂選項",
    setupVisualNote: "此處尚未提供 AI 圖片修訂。原始素材及文字海報仍須確認重用權限並經過審核。",
    setupRulesNote: "保留來源事實及指定詞彙。請在對話中要求 AI agent 依照此簡報提出修訂，再審閱已儲存版本。",
    setupPublicationSection: "3. 審核及發佈",
    setupPublicationNote: "新內容會保留為草稿。請逐項選擇保留草稿、批准後發佈或指定時間。逾時批准會暫停處理。來源掃描不會發佈帖文。",
    setupMonitoringSection: "4. 來源監察",
    setupMonitoringNote: "儲存不會啟動掃描或更改現有排程。儲存後，請啟用／套用監察以使用已儲存的頻率。檢查公開來源可能耗用點數。",
    setupMonitoringPaused: "監察已暫停",
    setupMonitoringActive: "監察已啟用",
    setupMonitoringLegacy: "已保留現有監察設定",
    setupEnable: "啟用／套用監察",
    setupPause: "暫停監察",
    setupSaveFirst: "請先儲存變更，再啟用監察。",
    setupSaved: "設定已儲存，監察狀態未有更改。",
    setupDone: "開啟內容收件匣",
    setupCustomCadence: "保留現有自訂頻率",
    setupQuietStart: "靜音時段開始",
    setupQuietEnd: "靜音時段結束",
    publicationTiming: "此版本的發佈時間",
    publicationDraft: "保留為草稿",
    publicationNow: "批准後發佈",
    publicationSchedule: "批准後按排程發佈",
    publicationLocalTime: "當地發佈日期及時間",
    publicationTimezone: "發佈時區（IANA）",
    publicationOffset: "UTC 偏移分鐘（選填，用於重複的當地時間）",
    publicationHint: "請將時間選項與內容版本一併儲存，再提交審核。選擇時間不代表排程已確認；錯過的時間會暫停處理，不會自動延後發佈。"
  }
};
