export const SETUP_COPY = {
  en: {
    setupFlow: "Source references → refine content and visuals → review → publish",
    setupSourcesSection: "Sources and destinations",
    setupSourcesNote: "Connected accounts are granted in workspace access settings. Public account changes below save immediately.",
    setupConnectedSources: "Connected sources",
    setupDestinations: "Publishing destinations",
    setupNoConnections: "None configured. Connect an account in workspace access settings.",
    setupCheckConnections: "Check for new connections",
    setupConnectionsFound: "New connections added: {names}",
    setupConnectionsNone: "No new connections found.",
    setupInstructions: "Instructions",
    setupInstructionsNote: "These are the workspace defaults. A post can override them.",
    setupContentPromptHint: "What the generated caption should say and how it should read — audience, angle, terms that must survive verbatim.",
    setupPosterPromptHint: "What each generated image should show and how it should look. Saved wording that asks for a text poster is kept, but new content is never made as a text poster — update it to describe a picture.",
    setupMonitoringSection: "Source monitoring",
    setupMonitoringSub: "Checks your sources on the cadence below. Public-source checks may use credits.",
    setupMonitoringPaused: "Monitoring is paused",
    setupMonitoringActive: "Monitoring is on",
    setupMonitoringLegacy: "Existing monitoring settings retained",
    setupSaveFirst: "Save changes before enabling monitoring.",
    setupSaved: "Settings saved. Monitoring was not changed.",
    setupCustomCadence: "Keep existing custom cadence",
    setupQuietStart: "From",
    setupQuietEnd: "to",
    setupQuietHoursNone: "No quiet hours",
    setupQuietHoursSet: "Quiet hours set",
    publicationTiming: "When",
    publicationDraft: "Keep as draft",
    publicationNow: "Publish now",
    publicationSchedule: "Schedule",
    publicationLocalTime: "Local publication date and time",
    publicationTimezone: "Publication timezone",
    publicationHint: "A chosen time is not a confirmed schedule."
  },
  "zh-HK": {
    setupFlow: "來源參考 → 修訂內容及視覺素材 → 審核 → 發佈",
    setupSourcesSection: "來源與發佈位置",
    setupSourcesNote: "已連結的帳戶在工作區權限設定中授權。下方公開帳戶的變更會即時儲存。",
    setupConnectedSources: "已連結來源",
    setupDestinations: "發佈位置",
    setupNoConnections: "尚未設定。請到工作區存取設定連接帳戶。",
    setupCheckConnections: "檢查新連結",
    setupConnectionsFound: "已新增連接：{names}",
    setupConnectionsNone: "沒有新連接。",
    setupInstructions: "指示",
    setupInstructionsNote: "這是工作區預設。個別帖文可以自行覆寫。",
    setupContentPromptHint: "生成的文案應表達甚麼、如何行文 — 目標讀者、切入角度、必須原樣保留的用詞。",
    setupPosterPromptHint: "每張生成圖片應呈現的內容和風格。已儲存而要求文字海報的指示會保留，但新內容不會製成文字海報，請改為描述圖片。",
    setupMonitoringSection: "來源監察",
    setupMonitoringSub: "按所選節奏檢查來源。檢查公開來源或會消耗點數。",
    setupMonitoringPaused: "監察已暫停",
    setupMonitoringActive: "監察已啟用",
    setupMonitoringLegacy: "已保留現有監察設定",
    setupSaveFirst: "請先儲存變更，再啟用監察。",
    setupSaved: "設定已儲存，監察狀態未有更改。",
    setupCustomCadence: "保留現有自訂頻率",
    setupQuietStart: "由",
    setupQuietEnd: "至",
    setupQuietHoursNone: "不設安靜時間",
    setupQuietHoursSet: "已設安靜時間",
    publicationTiming: "發佈時間",
    publicationDraft: "保留為草稿",
    publicationNow: "立即發佈",
    publicationSchedule: "排程發佈",
    publicationLocalTime: "當地發佈日期及時間",
    publicationTimezone: "發佈時區",
    publicationHint: "選擇時間不代表排程已確認。"
  }
};
