// G4 client path: accepted generated bytes are never re-delivered. A PNG bound
// for a JPEG-only destination chosen at Review gets an explicit "Prepare a
// JPEG copy" (a derived asset) and a separate acceptance that makes a new
// revision; an image whose provenance the server cannot vouch for is accepted
// again explicitly. Fake RPCs shaped like the server contract — not a browser
// proof (canvas conversion is injected here).
import { afterEach, describe, expect, it, vi } from "vitest";
import { createImageAcceptance, needsJpegCopy } from "../../src/src/client/image-acceptance.js";
import { createWizardState, releaseReviewImages, renderPublish, setBatch, setPublishError } from "../../src/src/client/steps.js";
import { findAll, installMinimalDom } from "./_helpers/minimal-dom";

type AnyRec = Record<string, any>;

const destinations = [
  { destinationBinding: "IG_DEST", label: "Instagram account", provider: "instagram", granted: true },
  { destinationBinding: "FB_DEST", label: "Facebook page", provider: "facebook", granted: true }
];

function pngItem(overrides: AnyRec = {}): AnyRec {
  return {
    id: "item1",
    batchId: "batch1",
    state: "drafting",
    revision: 3,
    caption: "第三稿內容文字",
    acceptedVisualMode: "ai_refinement",
    generatedImage: { id: "gm_png", ready: true, mimeType: "image/png" },
    // Destinations are chosen at Review, after drafting: nothing bound yet.
    destinationBindings: [],
    publications: [],
    sourceItem: { sourceLabel: "Synthetic source", provider: "instagram", text: "a post", id: "p1" },
    ...overrides
  };
}

function review(item: AnyRec, bindings: string[], extra: AnyRec = {}, error: AnyRec | null = null) {
  const { document } = installMinimalDom() as unknown as { document: { createElement(tag: string): any } };
  const root = document.createElement("div");
  let wizard: AnyRec = setBatch(createWizardState(), { id: "batch1", items: [item] } as never);
  wizard = { ...wizard, publishChoices: { item1: { bindings, intent: { publishMode: "publish_now", latePolicy: "hold" } } } };
  if (error) wizard = setPublishError(wizard as never, "item1", error) as AnyRec;
  const handlers = {
    loadGeneratedImage: (id: string) => Promise.resolve({ url: `blob:${id}`, mime: "image/png" }),
    onReviewImageState() {}, onOpenSettings() {}, onRefreshGrants() {}, onToggleBinding() {},
    onPublishIntent() {}, onEditCaption() {}, onSubmitItem() {}, onRetry() {}, onCheckManually() {}, onBack() {},
    imageAcceptanceState: () => ({ status: "idle" }),
    onPrepareJpeg: vi.fn(), onAcceptJpeg: vi.fn(), onReacceptImage: vi.fn(),
    ...extra
  };
  renderPublish(root, wizard as never, { locale: "en", summary: { destinations }, policy: {}, handlers } as never);
  return { root, handlers };
}

const action = (root: unknown, name: string) =>
  findAll(root as never, (e: any) => e.tagName === "BUTTON" && e.getAttribute("data-action") === name) as any[];

afterEach(() => releaseReviewImages());

describe("needsJpegCopy", () => {
  it("is true only for a PNG generated image filed to a chosen JPEG-only destination", () => {
    expect(needsJpegCopy(pngItem(), { bindings: ["IG_DEST"], destinations })).toBe(true);
    expect(needsJpegCopy(pngItem(), { bindings: ["FB_DEST"], destinations })).toBe(false);
    expect(needsJpegCopy(pngItem(), { bindings: [], destinations })).toBe(false);
    expect(needsJpegCopy(pngItem({ generatedImage: { id: "gm_jpg", ready: true, mimeType: "image/jpeg" } }), { bindings: ["IG_DEST"], destinations })).toBe(false);
    expect(needsJpegCopy(pngItem({ acceptedVisualMode: "keep_original" }), { bindings: ["IG_DEST"], destinations })).toBe(false);
  });
});

describe("Review offers a JPEG copy instead of re-delivering accepted bytes", () => {
  it("shows Prepare a JPEG copy when Instagram is chosen at Review for a pinned PNG", async () => {
    const { root, handlers } = review(pngItem(), ["IG_DEST"]);
    expect(root.textContent).toContain("The accepted image is a PNG, and a chosen destination accepts JPEG only.");
    const [prepare] = action(root, "prepare-jpeg");
    expect(prepare).toBeTruthy();
    await prepare.dispatchEvent({ type: "click" });
    expect(handlers.onPrepareJpeg).toHaveBeenCalledWith("item1");
  });

  it("offers nothing for a pinned JPEG or when no JPEG-only destination is chosen", () => {
    expect(action(review(pngItem({ generatedImage: { id: "gm_jpg", ready: true, mimeType: "image/jpeg" } }), ["IG_DEST"]).root, "prepare-jpeg")).toHaveLength(0);
    expect(action(review(pngItem(), ["FB_DEST"]).root, "prepare-jpeg")).toHaveLength(0);
  });

  it("turns into an explicit acceptance naming the new version once the copy is ready", async () => {
    const { root, handlers } = review(pngItem(), ["IG_DEST"], { imageAcceptanceState: () => ({ status: "ready", derivedId: "gm_jpeg" }) });
    expect(action(root, "prepare-jpeg")).toHaveLength(0);
    const [accept] = action(root, "accept-jpeg");
    expect(accept.textContent).toBe("Use the JPEG copy (version 4)");
    await accept.dispatchEvent({ type: "click" });
    expect(handlers.onAcceptJpeg).toHaveBeenCalledWith("item1");
  });

  it("answers a generated_image_format_stale refusal with the same action", () => {
    const { root } = review(pngItem(), ["FB_DEST"], {}, { code: "generated_image_format_stale", message: "Accept a JPEG copy." });
    expect(root.textContent).toContain("Prepare a JPEG copy, then submit again.");
    expect(action(root, "prepare-jpeg")).toHaveLength(1);
  });

  it("explains generated_image_review_required and offers re-acceptance", async () => {
    const { root, handlers } = review(pngItem({ generatedImage: { id: "gm_jpg", ready: true, mimeType: "image/jpeg" } }), ["FB_DEST"], {}, { code: "generated_image_review_required", message: "review" });
    expect(root.textContent).toContain("The accepted image's origin could not be confirmed.");
    const [again] = action(root, "reaccept-image");
    await again.dispatchEvent({ type: "click" });
    expect(handlers.onReacceptImage).toHaveBeenCalledWith("item1");
  });

  it("carries the revision's alt text to Review", () => {
    const { root } = review(pngItem({ altText: "A bowl of oats on a table", generatedImage: { id: "gm_jpg", ready: true, mimeType: "image/jpeg" } }), ["FB_DEST"]);
    expect(root.textContent).toContain("Alt text: A bowl of oats on a table");
  });
});

describe("image acceptance controller", () => {
  function controller(overrides: AnyRec = {}) {
    const rpc = {
      saveDerivedGeneratedImage: vi.fn(async () => ({ ok: true, id: "gm_jpeg", mimeType: "image/jpeg", digest: "sha256:x", reused: false })),
      saveRevision: vi.fn(async () => ({ ok: true, revision: 4 })),
      ...overrides
    };
    const loads: string[] = [];
    const acceptance = createImageAcceptance({
      rpc,
      loadImage: async (id: string) => { loads.push(id); return { url: `blob:${id}` }; },
      convert: async () => new Uint8Array([255, 216, 255, 217])
    });
    return { rpc, loads, acceptance };
  }

  it("prepares a derived JPEG, then accepting it creates one new revision pinned to the derived id", async () => {
    const { rpc, loads, acceptance } = controller();
    const item = pngItem();
    await acceptance.prepare(item);
    expect(loads).toEqual(["gm_png"]);
    expect(rpc.saveDerivedGeneratedImage).toHaveBeenCalledTimes(1);
    expect(rpc.saveDerivedGeneratedImage.mock.calls[0][0]).toMatchObject({ sourceMediaId: "gm_png", mimeType: "image/jpeg" });
    expect(acceptance.state("item1")).toMatchObject({ status: "ready", derivedId: "gm_jpeg" });
    // Preparing is not accepting.
    expect(rpc.saveRevision).not.toHaveBeenCalled();

    const saved = await acceptance.accept(item);
    expect(saved).toEqual({ ok: true, revision: 4 });
    expect(rpc.saveRevision).toHaveBeenCalledWith({
      batchItemId: "item1",
      expectedRevision: 3,
      acceptedVisualMode: "ai_refinement",
      acceptedGeneratedMediaId: "gm_jpeg"
    });
  });

  it("does not create duplicate derived assets or duplicate acceptances on repeated presses", async () => {
    const { rpc, acceptance } = controller();
    const item = pngItem();
    await Promise.all([acceptance.prepare(item), acceptance.prepare(item)]);
    await acceptance.prepare(item);
    expect(rpc.saveDerivedGeneratedImage).toHaveBeenCalledTimes(1);

    await Promise.all([acceptance.accept(item), acceptance.accept(item)]);
    expect(rpc.saveRevision).toHaveBeenCalledTimes(1);
    // The re-read post now pins the JPEG at version 4: nothing more to accept.
    const accepted = pngItem({ revision: 4, generatedImage: { id: "gm_jpeg", ready: true, mimeType: "image/jpeg" } });
    expect(await acceptance.accept(accepted)).toBeNull();
    expect(needsJpegCopy(accepted, { bindings: ["IG_DEST"], destinations })).toBe(false);
    expect(rpc.saveRevision).toHaveBeenCalledTimes(1);
  });

  it("keeps a copy prepared for an older revision from being accepted onto a newer one", async () => {
    const { rpc, acceptance } = controller();
    await acceptance.prepare(pngItem());
    expect(await acceptance.accept(pngItem({ revision: 5 }))).toBeNull();
    expect(rpc.saveRevision).not.toHaveBeenCalled();
  });

  it("reports a derived-asset refusal and accepts nothing", async () => {
    const { rpc, acceptance } = controller({
      saveDerivedGeneratedImage: vi.fn(async () => ({ ok: false, code: "generated_media_not_image", message: "That file is not an image." }))
    });
    await acceptance.prepare(pngItem());
    expect(acceptance.state("item1")).toMatchObject({ status: "failed", message: "That file is not an image." });
    expect(await acceptance.accept(pngItem())).toBeNull();
    expect(rpc.saveRevision).not.toHaveBeenCalled();
  });

  it("re-accepts the pinned image explicitly, once", async () => {
    const { rpc, acceptance } = controller();
    const item = pngItem();
    await Promise.all([acceptance.reaccept(item), acceptance.reaccept(item)]);
    expect(rpc.saveRevision).toHaveBeenCalledTimes(1);
    expect(rpc.saveRevision).toHaveBeenCalledWith({ batchItemId: "item1", expectedRevision: 3, acceptedVisualMode: "ai_refinement", acceptedGeneratedMediaId: "gm_png" });
  });
});
